import { Injectable, NotFoundException, BadRequestException, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { BibleStudy, BibleStudyStatus } from '../../entities/bible-study.entity';
import { Church } from '../../entities/church.entity';
import { CreateBibleStudyDto } from './dto/create-bible-study.dto';
import { UpdateBibleStudyDto } from './dto/update-bible-study.dto';

@Injectable()
export class BibleStudyService {
  private readonly logger = new Logger(BibleStudyService.name);
  
  constructor(
    @InjectRepository(BibleStudy)
    private bibleStudyRepository: Repository<BibleStudy>,
    @InjectRepository(Church)
    private churchesRepository: Repository<Church>,
  ) {}

  async findAll(churchId: string): Promise<BibleStudy[]> {
    return this.bibleStudyRepository.find({ 
      where: { churchId },
      relations: ['author', 'church'],
      order: { createdAt: 'DESC' } 
    });
  }

  async findOne(id: string, churchId: string): Promise<BibleStudy> {
    const bibleStudy = await this.bibleStudyRepository.findOne({ 
      where: { id, churchId },
      relations: ['author', 'church'] 
    });
    if (!bibleStudy) {
      throw new NotFoundException(`Bible study with ID ${id} not found`);
    }
    return bibleStudy;
  }

  async create(createBibleStudyDto: CreateBibleStudyDto, userId: string, churchId: string): Promise<BibleStudy> {
    const newBibleStudy = this.bibleStudyRepository.create({
      ...createBibleStudyDto,
      authorId: userId,
      churchId,
    });

    return this.bibleStudyRepository.save(newBibleStudy);
  }

  async update(id: string, updateBibleStudyDto: UpdateBibleStudyDto, churchId: string): Promise<BibleStudy> {
    // Check if bible study exists
    await this.findOne(id, churchId);

    // Update bible study
    await this.bibleStudyRepository.update({ id, churchId }, updateBibleStudyDto);
    return this.findOne(id, churchId);
  }

  async updateStatus(id: string, status: BibleStudyStatus, churchId: string): Promise<BibleStudy> {
    // Check if bible study exists
    const bibleStudy = await this.findOne(id, churchId);
    
    // Update status
    bibleStudy.status = status;
    
    return this.bibleStudyRepository.save(bibleStudy);
  }

  async getChurchWithSubscription(churchId: string): Promise<Church> {
    this.logger.log(`Getting church with subscription for church ID ${churchId}`);
    
    const church = await this.churchesRepository.findOne({ where: { id: churchId } });
    
    if (!church) {
      throw new NotFoundException(`Church with ID ${churchId} not found`);
    }
    
    return church;
  }

  async generateAiExplanations(id: string, verses: string[], churchId: string): Promise<BibleStudy> {
    this.logger.log(`Generating AI explanations for Bible study ${id} in church ${churchId}`);
    // This is a placeholder for AI bible study generation logic
    // In a real implementation, this would call the OpenAI API
    
    try {
      // Find the Bible study
      const bibleStudy = await this.findOne(id, churchId);
      
      // Add AI-generated explanations
      bibleStudy.aiGeneratedExplanations = verses.reduce((acc, verse) => {
        acc[verse] = 'This explanation was generated by AI. Content will be replaced with actual AI-generated text.';
        return acc;
      }, {});

      const savedBibleStudy = await this.bibleStudyRepository.save(bibleStudy);
      this.logger.log(`Successfully generated AI explanations for Bible study ${id}`);
      return savedBibleStudy;
    } catch (error) {
      this.logger.error(`Error generating AI explanations: ${error.message}`, error.stack);
      throw new BadRequestException(`Failed to generate explanations: ${error.message}`);
    }
  }

  async remove(id: string, churchId: string): Promise<void> {
    const bibleStudy = await this.findOne(id, churchId);
    await this.bibleStudyRepository.remove(bibleStudy);
  }
}
