import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { BibleStudy, BibleStudyStatus } from '../../entities/bible-study.entity';

@Injectable()
export class BibleStudyService {
  constructor(
    @InjectRepository(BibleStudy)
    private bibleStudyRepository: Repository<BibleStudy>,
  ) {}

  async findAll(churchId: string): Promise<BibleStudy[]> {
    return this.bibleStudyRepository.find({ 
      where: { churchId },
      relations: ['author', 'church'],
      order: { createdAt: 'DESC' } 
    });
  }

  async findOne(id: string, churchId: string): Promise<BibleStudy> {
    const bibleStudy = await this.bibleStudyRepository.findOne({ 
      where: { id, churchId },
      relations: ['author', 'church'] 
    });
    if (!bibleStudy) {
      throw new NotFoundException(`Bible study with ID ${id} not found`);
    }
    return bibleStudy;
  }

  async create(createBibleStudyDto: any, userId: string, churchId: string): Promise<BibleStudy> {
    const newBibleStudy = this.bibleStudyRepository.create({
      ...createBibleStudyDto,
      authorId: userId,
      churchId,
    });

    return this.bibleStudyRepository.save(newBibleStudy);
  }

  async update(id: string, updateBibleStudyDto: any, churchId: string): Promise<BibleStudy> {
    // Check if bible study exists
    await this.findOne(id, churchId);

    // Update bible study
    await this.bibleStudyRepository.update({ id, churchId }, updateBibleStudyDto);
    return this.findOne(id, churchId);
  }

  async updateStatus(id: string, status: BibleStudyStatus, churchId: string): Promise<BibleStudy> {
    // Check if bible study exists
    const bibleStudy = await this.findOne(id, churchId);
    
    // Update status
    bibleStudy.status = status;
    
    return this.bibleStudyRepository.save(bibleStudy);
  }

  async generateAiExplanations(id: string, verses: string[], churchId: string): Promise<BibleStudy> {
    // This is a placeholder for AI bible study generation logic
    // In a real implementation, this would call the OpenAI API
    
    // Find the Bible study
    const bibleStudy = await this.findOne(id, churchId);
    
    // Add AI-generated explanations
    bibleStudy.aiGeneratedExplanations = verses.reduce((acc, verse) => {
      acc[verse] = 'This explanation was generated by AI. Content will be replaced with actual AI-generated text.';
      return acc;
    }, {});

    return this.bibleStudyRepository.save(bibleStudy);
  }

  async remove(id: string, churchId: string): Promise<void> {
    const bibleStudy = await this.findOne(id, churchId);
    await this.bibleStudyRepository.remove(bibleStudy);
  }
}
